FROM registry.redhat.io/openshift3/jenkins-slave-base-rhel7
LABEL com.redhat.component="jenkins-agent-python-rhel7-container" \
      name="jenkins-agent-python-rhel7" \
      version="3.6" \
      architecture="x86_64" \
      io.k8s.display-name="Jenkins Agent Python" \
      io.k8s.description="The jenkins build agent Python" \
      io.openshift.tags="openshift,jenkins,agent,python,python3,builder"

ENV PYTHON_VERSION=3.6 \
    PATH=/opt/rh/rh-python36/root/usr/bin:$HOME/.local/bin/:$PATH \
    LD_LIBRARY_PATH=/opt/rh/rh-python36/root/usr/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

COPY contrib/bin/scl_enable /usr/local/bin/scl_enable

RUN yum-config-manager --enable rhel-server-rhscl-7-rpms && \
    INSTALL_PKGS="rh-python36-python-devel rh-python36-python-pip rh-python36-python-setuptools gcc libcurl-devel httpd httpd-devel" && \
    yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    rpm -e --nodeps redhat-logos && \
    yum clean all -y && \
    rm -rf /var/cache/yum && \
    chown -R 1001:0 $HOME && \
    chmod -R g+rw $HOME

USER 1001
